### ISSUE TITLE
New PowerShell

### ISSUE THREAD

**Issue by Karnith** [bitsofinfo/powershell-command-executor#6]
will this work with the new open source PowerShell?

https://github.com/PowerShell/PowerShell

also, I'd like to have a private conversation with you when you have the time. It could be mutually beneficial.

Thanks,
Matthew

**Comment by bitsofinfo** [comment]
This core functionality of this tool ( stateful-process-command-proxy ) can interact with any shell process that supports interaction over STDIN/STDERR/STDOUT streams.

So... if the the OSS variant of PS works like any other shell via such mechanisms, then I don't see why it wouldn't.

If you would like to chat, you can email/message me on github.
